Ensure unique pharmacy urls
dodekatheon/zeus pull request #18
Opened 2020-12-19 22:31 UTC by chrysanthos

This PR introduces a new field `slug`. This makes sure the seo url is always the same even if Laravel decides to change how it works at some point.

Additionally it solves the issue where you could basically visit `/678/farmakeia-giannakis` and `/678/its-me` and see the same thing since the page only depends on the am attribute. 

Some other minor refactors as well.

2020-12-20 08:34 UTC, gregkos requested changes
I am okay with the idea, although the execution needs more work. Can you give me an example of pharmacies that throw errors due to having the same name? The url was based on AM only to avoid such problems. 🤔

2020-12-20 08:34 UTC, gregkos commented on app/Http/Controllers/PagesController.php
> -<?php
If we are deleting this, restructure all the views as well...

2020-12-20 08:34 UTC, gregkos commented on app/Models/Pharmacy.php
> +    public function getSlugOptions() : SlugOptions
We need to update the coordinate filling and the single pharmacy map to use this then.

2020-12-20 08:34 UTC, gregkos commented on composer.json
> +        "spatie/laravel-sluggable": "^2.6",
I get setting the slug to a db value, but did we really need a whole new package for that..?

2020-12-20 08:34 UTC, gregkos commented on routes/web.php
> +        Route::resource('pharmacies', \App\Http\Controllers\Admin\PharmacyController::class);
Import and remove FQN

2020-12-20 21:34 UTC, chrysanthos commented on app/Models/Pharmacy.php
> +    public function getSlugOptions() : SlugOptions
Not sure what you mean

2020-12-20 21:36 UTC, chrysanthos commented on composer.json
> +        "spatie/laravel-sluggable": "^2.6",
We don't really, but we are fancy and this allows to reduce our code and our bugs 😸

2020-12-20 21:39 UTC, chrysanthos commented on app/Http/Controllers/PagesController.php
> -<?php
In another PR

2020-12-21 17:59 UTC, gregkos commented on app/Models/Pharmacy.php
> +    public function getSlugOptions() : SlugOptions
Look at `pharmacies:fill-coordinates`

2020-12-21 17:59 UTC, gregkos commented on app/Models/Pharmacy.php
> +    public function getSlugOptions() : SlugOptions
And also at `single.blade.php`, but I hope that one was obvious

2020-12-21 20:01 UTC, gregkos requested changes

2020-12-21 20:14 UTC, gregkos approved these changes

2020-12-21 20:46 UTC, merged