Fix responsiveness
dodekatheon/zeus pull request #22
Opened 2020-12-21 21:19 UTC by chrysanthos

2020-12-22 19:02 UTC, gregkos requested changes

2020-12-22 19:02 UTC, gregkos commented on resources/views/layouts/partials/header.blade.php
> +                        Πως Λειτουργεί
???

2020-12-22 19:02 UTC, gregkos commented on resources/views/pages/pharmacies/single.blade.php
> +                                {{ $pharmacy->address }} @isset($pharmacy->additional_address){{ $pharmacy->additional_address }})@endisset
You dropped the opening parenthesis though

2020-12-23 10:32 UTC, chrysanthos commented on resources/views/layouts/partials/header.blade.php
> +                        Πως Λειτουργεί
???

2020-12-23 10:33 UTC, chrysanthos commented on resources/views/pages/pharmacies/single.blade.php
> +                                {{ $pharmacy->address }} @isset($pharmacy->additional_address){{ $pharmacy->additional_address }})@endisset
Nicr catch

2020-12-23 10:43 UTC, gregkos commented on resources/views/layouts/partials/header.blade.php
> +                        Πως Λειτουργεί
"Μου είπε πως λειτουργεί" = "Μου είπε ότι λειτουργεί", ενώ "Μου είπε πώς λειτουργεί" = "Μου είπε τον τρόπο με τον οποίο λειτουργεί". Όταν το πως δεν έχει τόνο σημαίνει "ότι". Γιατί να τον αφαιρέσεις από εδώ;

2020-12-23 14:33 UTC, chrysanthos commented on resources/views/layouts/partials/header.blade.php
> +                        Πως Λειτουργεί
Είχα την εντύπωση ότι μπαίνει τόνος μόνο όταν είναι ερώτηση, όχι;

2020-12-23 14:37 UTC, gregkos commented on resources/views/layouts/partials/header.blade.php
> +                        Πως Λειτουργεί
AFAIK όταν προσδίδει ερώτηση. Είτε άμεση είτε έμμεση 🤷🏼‍♂️

2020-12-23 16:21 UTC, chrysanthos commented on resources/views/layouts/partials/header.blade.php
> +                        Πως Λειτουργεί
Οι πηγές μου λένε μπαίνει μόνο σε ερωτήσεις 😅

2020-12-23 16:29 UTC, gregkos commented on resources/views/layouts/partials/header.blade.php
> +                        Πως Λειτουργεί
Δεν μπορώ να καταλάβω πώς γίνεται να λένε τέτοιο πράγμα. See what I did there? 😂

2021-01-06 10:32 UTC, gregkos approved these changes

2021-01-06 10:32 UTC, merged