GitHub Actions integration
dodekatheon/zeus pull request #6
Opened 2020-12-03 19:35 UTC by gregkos

2020-12-03 19:38 UTC, chrysanthos commented on .github/workflows/laravel.yml
> +    branches: [ master ]
```suggestion
on: [push]
```

2020-12-03 19:40 UTC, gregkos commented on .github/workflows/laravel.yml
> +    branches: [ master ]
Why on every push?

2020-12-03 20:54 UTC, chrysanthos commented on .github/workflows/laravel.yml
> +    branches: [ master ]
Isn't the purpose of running tests to know if they pass **before** you merge? We won't know if the tests pass on PRs. Unless the last 2 lines mean "run when target branch is master" but even then why not run them every time?

2020-12-03 21:00 UTC, gregkos commented on .github/workflows/laravel.yml
> +    branches: [ master ]
Of course they run before you merge. The original block says: run when something is pushed directly to master or for PRs targeting master. Same as the GitLab implementation we are both familiar with, the pipeline runs for every push to this PR - look below this thread. Running the pipeline for every single push on every single branch is counter-productive and will burn through our plan minutes within a week. At the same time, the purpose of this pipeline is not to run tests, it will be the full build-test-deploy action. The PR was opened automatically when the Laravel workflow was selected, it will keep being worked on.

2020-12-10 21:31 UTC, gregkos commented on .github/workflows/laravel.yml
> +    branches: [ master ]
Bump, @chrysanthos

2020-12-12 13:14 UTC, chrysanthos commented on .github/workflows/laravel.yml
> +    branches: [ master ]
I still thing we should always run the tests. We have a ton of minutes and we do a PR per week or something so there is no way we will run out of minutes.

2020-12-12 13:18 UTC, chrysanthos requested changes

2020-12-12 13:18 UTC, chrysanthos commented on .github/workflows/default.yml
> +        run: exit 1
We should be able to run tests and deploy even when cache fails for some reason. I think we should safely remove this..

2020-12-12 13:18 UTC, chrysanthos commented on .github/workflows/default.yml
> +        run: php -r "file_exists('.env') || copy('.env.example', '.env');"
```suggestion
        run: php -r "file_exists('.env') || copy('.env.github', '.env');"
```

2020-12-12 14:27 UTC, gregkos commented on .github/workflows/laravel.yml
> +    branches: [ master ]
You confuse me... With my code, it runs for every push on every PR. With your suggested change, it will run on every single push for any branch in the entire repo. How would that be useful?!

2020-12-12 14:28 UTC, gregkos commented on .github/workflows/default.yml
> +        run: exit 1
If there is no cache there is no vendor folder, so neither the tests nor the deployed site will work :)

2020-12-12 14:30 UTC, gregkos commented on .github/workflows/default.yml
> +        run: php -r "file_exists('.env') || copy('.env.example', '.env');"
There needs to be a .env.github for this to work though, there is none right now

2020-12-12 15:28 UTC, chrysanthos commented on .github/workflows/laravel.yml
> +    branches: [ master ]
I shouldn't be forced to create a PR to run the tests. I'd like to know everything is ok before creating a PR. Anyway whatever

2020-12-12 15:29 UTC, chrysanthos commented on .github/workflows/default.yml
> +        run: php -r "file_exists('.env') || copy('.env.example', '.env');"
Create it then 😂

2020-12-12 15:32 UTC, chrysanthos commented on .github/workflows/default.yml
> +        run: php -r "file_exists('.env') || copy('.env.example', '.env');"
You can run the composer install command after restoring the cache without a conditional.

2020-12-12 15:32 UTC, chrysanthos commented on .github/workflows/default.yml
> +        run: exit 1
You can run the composer install command after restoring the cache without a conditional.

2020-12-12 21:25 UTC, gregkos commented on .github/workflows/default.yml
> +        run: exit 1
That adds overhead. Extra attempts to install.

2020-12-12 21:26 UTC, gregkos commented on .github/workflows/default.yml
> +        run: php -r "file_exists('.env') || copy('.env.example', '.env');"
Overengineering 🎶 Done

2020-12-12 21:28 UTC, gregkos commented on .github/workflows/laravel.yml
> +    branches: [ master ]
GitHub shouldn't be forced to run your tests for you. Run your tests locally. The pipeline only exists to show the reviewers your changes are not breaking the tests. They are not your personal runner.

2020-12-13 07:52 UTC, chrysanthos approved these changes

2020-12-15 20:14 UTC, chrysanthos requested changes

2020-12-15 20:14 UTC, chrysanthos commented on .github/workflows/pipeline.yml
> +            composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
Add `--no-dev`

2020-12-15 20:38 UTC, chrysanthos commented on .github/workflows/pipeline.yml
> +            git pull
I think pull fetches all branches, might be a good idea to add make it `git pull origin master`?

2020-12-16 17:28 UTC, gregkos commented on .github/workflows/pipeline.yml
> +            composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
😲 Good catch!

2020-12-16 17:29 UTC, gregkos commented on .github/workflows/pipeline.yml
> +            git pull
I think you're thinking of `git fetch` but let's update it to be safe 👌🏼

2020-12-16 17:35 UTC, gregkos commented on .github/workflows/pipeline.yml
> +            git pull
Scratch that, I tried it locally and it merged master into my current branch. Not changing it as this might be unsafe if we have a different branch deployed for whatever reason...

2020-12-16 20:41 UTC, chrysanthos approved these changes

2020-12-17 17:58 UTC, merged